version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=challengedb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports: 
      - "5432:5432"
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db