# Generated by Django 3.0.5 on 2020-05-04 05:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('owner', models.CharField(max_length=500, null=True)),
                ('accountid', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('permissions', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=500)),
                ('industry', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.AnalyticsAccount')),
            ],
        ),
        migrations.CreateModel(
            name='LogEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('logdescription', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timeresponse', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(default='N/A', max_length=50)),
                ('credentials', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewid', models.IntegerField()),
                ('viewname', models.CharField(max_length=500)),
                ('currency', models.CharField(max_length=3)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('timezone', models.CharField(max_length=200)),
                ('userid', models.IntegerField()),
                ('propid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.AnalyticsProperties')),
            ],
        ),
    ]
