# Generated by Django 3.0.5 on 2020-04-25 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('state_short', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('district', models.CharField(blank=True, max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.User')),
            ],
        ),
    ]
