# Generated by Django 3.0.5 on 2020-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0002_auto_20200426_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
