# Generated by Django 3.0.5 on 2020-04-27 23:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0004_user_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credentials',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
