# Generated by Django 3.0.5 on 2020-04-27 22:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0004_user_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name=''),
        ),
    ]
