# Generated by Django 3.0.5 on 2020-05-02 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0005_auto_20200427_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('permissions', models.CharField(max_length=300)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propid', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=500)),
                ('industry', models.CharField(max_length=50)),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.AnalyticsAccount')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewid', models.IntegerField()),
                ('viewname', models.CharField(max_length=500)),
                ('coin', models.CharField(max_length=3)),
                ('created', models.DateTimeField(default=datetime.date(2020, 5, 2))),
                ('updated', models.DateTimeField(default=datetime.date(2020, 5, 2))),
                ('timezone', models.CharField(max_length=200)),
                ('propid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.AnalyticsProperties')),
            ],
        ),
        migrations.CreateModel(
            name='LogEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdescription', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=datetime.date(2020, 5, 2))),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challengeApp.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
