# Generated by Django 3.0.5 on 2020-05-02 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0006_auto_20200502_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 19, 57, 42, 621079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='analyticsviews',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 19, 57, 42, 621079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logevents',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 19, 57, 42, 622078, tzinfo=utc)),
        ),
    ]
