# Generated by Django 3.0.5 on 2020-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0007_auto_20200502_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsaccount',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='analyticsviews',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analyticsviews',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logevents',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
