# Generated by Django 3.0.5 on 2020-04-27 22:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0007_auto_20200427_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
