# Generated by Django 3.0.5 on 2020-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0008_auto_20200502_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsproperties',
            name='propid',
            field=models.CharField(max_length=100),
        ),
    ]
