# Generated by Django 3.0.5 on 2020-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0008_auto_20200427_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credentials',
            field=models.CharField(default='N/A', max_length=9999),
        ),
    ]
