# Generated by Django 3.0.5 on 2020-05-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0009_auto_20200502_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsviews',
            old_name='coin',
            new_name='currency',
        ),
        migrations.AlterField(
            model_name='logevents',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
