# Generated by Django 3.0.5 on 2020-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0010_auto_20200502_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsaccount',
            name='owner',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
