# Generated by Django 3.0.5 on 2020-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0012_logevents_timeresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevents',
            name='timeresponse',
            field=models.TimeField(null=True),
        ),
    ]
