# Generated by Django 3.0.5 on 2020-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0013_auto_20200503_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevents',
            name='timeresponse',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
