# Generated by Django 3.0.5 on 2020-05-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0014_auto_20200503_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsproperties',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticsviews',
            name='userid',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
