# Generated by Django 3.0.5 on 2020-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0015_auto_20200503_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsviews',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analyticsviews',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
